[nfs]
172.31.8.253 ansible_ssh_user='ec2-user'

[webservers]
172.31.13.242 ansible_ssh_user='ec2-user'
172.31.13.169 ansible_ssh_user='ec2-user'

[db]
172.31.15.63 ansible_ssh_user='ec2-user'

[lb]
172.31.12.189 ansible_ssh_user='ubuntu'




