---
# tasks for nginx
- name: install nginx on the webserver
  ansible.builtin.yum:
    name: nginx
    state: present

- name: ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: install PHP and required PHP modules
  ansible.builtin.yum:
    name:
      - php
      - php-mysqlnd
      - php-gd
      - php-curl
    state: present


 
