---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: true
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
<<<<<<< HEAD
      yum3:
=======
      dnf:
>>>>>>> 24b5f919c5209592972132d7a99fc55958ead643
        name: wireshark
        state: latest
   

- name: update Loadbalancer server
  hosts: lb
  become: true
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
