---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: true
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      dnf:
        name: wireshark
        state: latest
   

- name: update Loadbalancer server
  hosts: lb
  become: true
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
