---
- hosts: db
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/db.yaml

- hosts: nginx
- name: nginx assignment
  ansible.builtin.import_playbook: ../static-assignments/nginx.yaml




  


  
 




