---
- hosts: db
  tasks:
    - name: database assignment
      import_playbook: ..\static-assignments\db.yaml

- hosts: nginx
  tasks:
    - name: nginx assignment
      import_playbook: ..\static-assignments\nginx.yaml






  


  
 




