---
- hosts: db
  tasks:
    - name: Include DB playbook
      include_playbook: ../static-assignments/db.yaml

- hosts: nginx
  tasks:
    - name: Include Nginx playbook
      include_playbook: ../static-assignments/nginx.yaml






  


  
 




