---
- name: installing database
  hosts: db
- name: db assignment
  import_playbook: ..\\static-assignments\\db.yaml


- name: installing nginx
  hosts: nginx
- name: nginx assignment
  import_playbook: ..\\static-assignments\\nginx.yaml 









  


  
 




