---
- hosts: db
  tasks:
    - name: database assignment
      include_playbook: ../static-assignments/db.yaml

- hosts: nginx
  tasks:
    - name: nginx assignment
      include_playbook: ../static-assignments/nginx.yaml





  


  
 




