---

# tasks for webservers

- name: Install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: Install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/BusisiwePieterson/NFS-Website-Solution.git
    dest: /var/www/html
    force: yes

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

<<<<<<< HEAD
=======

>>>>>>> 39e0cf880678025721f1f59358390e6039e1e169
- name: Recursively remove /var/www/html directory
  become: true
  ansible.builtin.file:
    path: /var/www/html
<<<<<<< HEAD
    state: absent
=======
    state: absent 
>>>>>>> 39e0cf880678025721f1f59358390e6039e1e169
